databases:
  - name: whatsapp-crm-db
    databaseName: whatsapp_crm
    user: whatsapp_crm
    plan: free
    region: singapore

services:
  - type: web
    runtime: static
    name: whatsapp-crm-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://whatsapp-crm-backend-g4xx.onrender.com/api
  - type: web
    name: whatsapp-crm-backend
    runtime: docker
    rootDir: backend
    plan: free
    region: singapore
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_KEY
        value: base64:fWnt+C0E96xRXM4thtAbrQw+clHvCWlwnvuX9xMM83s=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: whatsapp-crm-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: whatsapp-crm-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: whatsapp-crm-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: whatsapp-crm-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: whatsapp-crm-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: PROVIDER_TOKEN
        generateValue: true
      - key: WHATSAPP_SERVICE_URL
        sync: false
  - type: web
    name: whatsapp-crm-whatsapp
    runtime: docker
    rootDir: whatsapp
    plan: free
    region: singapore
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: "10000"
      - key: LARAVEL_URL
        value: https://whatsapp-crm-backend-g4xx.onrender.com
      - key: PROVIDER_TOKEN
        fromService:
          name: whatsapp-crm-backend
          type: web
          envVarKey: PROVIDER_TOKEN
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
